### ISSUE TITLE
Meta: consider changing this issue template to include the full AI chat log

### ISSUE THREAD

**Issue by zcorpan** [mdn/yari#10751]
### What is the issue with the answer?

In https://github.com/mdn/ai-feedback/issues/37 I filed an issue via the link on https://developer.mozilla.org/en-US/plus/ai-help , but the prefilled fields for "What did AI Help answer?" and "What MDN pages did AI Help consult?" only included the last question. It may be better to have a single field for the full chat log.

### How would you categorize this issue?

- [ ] The answer is harmful / unsafe.
- [ ] The answer is not correct.
- [ ] The answer is not helpful.
- [ ] The answer is outdated.

### What did you ask?

-

### What did AI Help answer?

-

### What MDN pages did AI Help consult?

-
