### ISSUE TITLE
[tracker] Yari1 launch checklist

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1084]
### Yari Launch Checklist

- [ ] Resolve what to do with localized content
    - [ ] https://github.com/mdn/yari/issues/1076
- [ ] Move the content from yari into new `mdn/mdn-content` repo and test it
- [ ] Need to determine and implement a policy for `mdn/mdn-content` repo's PR's (e.g., auto-merge if linters/tests pass?)
- [ ] `mdn/kuma` work for launch
    - [ ] Disable the following URL's/views:
        - `/<locale>/dashboards/` and all of its children
        - `/<locale>/docs.json`
        - `/<locale>/unsubscribe`
- [ ] Do we need to bleach the kumascript-rendered HTML and/or filter its `<iframe>` hosts? In other words, do we need to add some more pieces from [this](https://github.com/mdn/kuma/blob/0b114c8adf1a387e8b80ba4577b9e69928b68a49/kuma/wiki/content.py#L181) to somewhere around [here](https://github.com/mdn/yari/blob/526b13a069c846740d71e9d581c0ca51ca5558b9/kumascript/index.js#L54)?
- [ ] Handle [fundamental redirects](https://github.com/mdn/kuma/blob/master/kuma/redirects/redirects.py):
    - [ ] Implement fundamental redirects in JS
    - [ ] Modify [`resolve`](https://github.com/mdn/yari/blob/526b13a069c846740d71e9d581c0ca51ca5558b9/content/redirect.js#L24) to include fundamental redirects
    - [ ] Modify the importer to consider the fundamental redirects and exclude documents that are redirected to external domains? I'm thinking of the [`WebExtensions` documents](https://github.com/mdn/kuma/blob/0b114c8adf1a387e8b80ba4577b9e69928b68a49/kuma/redirects/redirects.py#L1026).
    - [ ] Include the fundamental redirects within the planned CloudFront origin-response handler (Lambda@Edge)
- [ ] Create list of documents that either need to be deleted or updated
    - [ ] https://developer.mozilla.org/en-US/docs/MDN and others under its document tree (e.g., many docs talk about MDN as a Wiki)
    - [ ] https://developer.mozilla.org/en-US/docs/MDN/Doc_status and all of its sub-pages should be removed
- [ ] Resolve all file-attachment URL's within documents and download their corresponding content into the `mdn-content` repo (NOTE: I think @peterbe is already planning to add this feature to his flaw fixer). Here are the possible signatures of the file-attachment URL's that we'll need to handle:
    - `/files/<file-id>/<filename>`
    - `/@api/deki/files/<file-id>/<filename>`
    - `https://mdn.mozillademos.org/files/<file-id>/<filename>`
    - `https://media.prod.mdn.mozit.cloud/attachments/...`
    - `/<locale>/docs/...$samples/<sample-name>/files/<file-id>/<filename>` (NOTE: I don't see any of this type within our non-archived content)
- [ ] Fix the few old sample URL's referenced in the content (I found 5 of them)(e.g. https://mdn.mozillademos.org/en-US/docs/Web/API/HTMLImageElement/height$samples/Example --> https://mdn.mozillademos.org/en-US/docs/Web/API)/HTMLImageElement/height/_samples_/Example)
    <img width="1190" alt="image" src="https://user-images.githubusercontent.com/3743693/90570913-8ce53700-e165-11ea-975b-00a6ac8dfb53.png">
- [ ] Make Fiori look good (not great or perfect or OKish)
- [ ] Close all [Yari1 Milestone issues](https://github.com/mdn/yari/issues?q=is%3Aopen+is%3Aissue+milestone%3AYari1)
- [ ] Finish the deployer
    - [ ] Cron job Action should keep populating an S3 bucket reliably
    - [ ] Upload Lambda@Edge source code (in progress)
    - [ ] Modify current S3 upload code to work seamlessly with `maws`-define AWS credentials (minor)
- [ ] AWS work
    - [ ] Create new `prod` and `stage` S3 buckets for the Yari document content, static and sitemap files (`dev` is already created)
    - [ ] Define changes and change plan required for primary `stage` and `prod` CDN's
- [ ] Review README for writers willing to contribute
- [ ] Prepare communication
- [ ] Have a post-migration checklist (e.g. fix fixable flaws, enabling stricter flaw checking in PR builds)

### Notes
- Experimenting with (ab)using GitHub issues to manage the tracking of remaining issues to launch Yari1
- Disclaimer: **Yari1** is the code word for launching Yari into production but only for the documents. We build Yari, upload built static files to S3 and have CloudFront act as a "cache". If it's in S3, great, return it. If it's not in S3 fall back to Django. Also, Yari1 means no non-document pages yet use this JAMStack approach: no home page, site search, sign-up, subscriptions, 404.

**Comment by escattone** [comment]
Closing this since I've created issues for all of the items in this checklist and placed them within the [`Yari1` milestone](https://github.com/mdn/yari/milestone/25).
