### ISSUE TITLE
Tracker - MDN Fiori - Header

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1204]
Tracker issue for the MDN Fiori - Header milestone

- [x] [Rotate arrows in main menu(mobile) on interaction](https://github.com/mdn/yari/issues/1166)
- [x] [Add header search component](https://github.com/mdn/yari/issues/1130)
- [x] [Add user menu component](https://github.com/mdn/yari/issues/1131)
- [x] [Main menu tests](https://github.com/mdn/yari/issues/1125)

No longer part of Yari 1 milestone

- [ ] [Improve accessibility of main menu](https://github.com/mdn/yari/issues/1124)
- [ ] [User menu component accessibility](https://github.com/mdn/yari/issues/1168)
