### ISSUE TITLE
Tracker - MDN Fiori - Sidebar

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1206]
Tracker issue for the MDN Fiori - Sidebar milestone

- [x] [Sidebar components and styles](https://github.com/mdn/yari/issues/1137)
- [x] [Add new TOC to reference and styling](https://github.com/mdn/yari/issues/1142)
- [x] [Sidebar icons aren't "outside the text"](https://github.com/mdn/yari/issues/1109)
