### ISSUE TITLE
Tracker - MDN Fiori - Main Content

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1207]
Tracker issue for the MDN Fiori - Main Content milestone

- [x] [Forms](https://github.com/mdn/yari/issues/1121)
- [ ] [Meta Information](https://github.com/mdn/yari/issues/1132)
- [x] [Typescale](https://github.com/mdn/yari/issues/1170)
- [x] [Color palette](https://github.com/mdn/yari/issues/1171)
- [x] [Table styles](https://github.com/mdn/yari/issues/1172)
- [ ] [Link styles](https://github.com/mdn/yari/issues/1173)
- [x] [Iconography](https://github.com/mdn/yari/issues/1174)
- [x] [Buttons](https://github.com/mdn/yari/issues/1175)
- [ ] [Note cards/backgrounds](https://github.com/mdn/yari/issues/1133)
- [x] [Add code example table to Storybook](https://github.com/mdn/yari/issues/1136)
- [x] [Add browser compat table to Storybook](https://github.com/mdn/yari/issues/1143)
- [x] [Interactive examples style](https://github.com/mdn/yari/issues/1176)
- [x] [Modals](https://github.com/mdn/yari/issues/1179)
- [x] [BCD table in "text-decoration-style" page is broken when notes are expanded](https://github.com/mdn/yari/issues/1167)
- [ ] [readOnly indicators hard to read in kumastyles](https://github.com/mdn/yari/issues/1007)
- [ ] [good/bad example pre tags styling](https://github.com/mdn/yari/issues/1066)
- [x] [prevnext buttons messed up](https://github.com/mdn/yari/issues/1118)
- [x] [Some base64 images in used CSS](https://github.com/mdn/yari/issues/1165)
- [x] [Custom link component](https://github.com/mdn/yari/issues/1139)

**Comment by schalkneethling** [comment]
Closing as remaining and new issues are gathered here:
https://github.com/mdn/yari/milestone/32
