### ISSUE TITLE
Task List: Sprint 1: Issue and PR Triage

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5127]
## Milestone

[Sprint 1: Issue and PR Triage](https://github.com/mdn/yari/milestone/36)

#### Oldest 10

- [x] [Italic inside bold is not converted correctly from HTML to MD](https://github.com/mdn/yari/issues/4648)
- [x] [README.md and signed PRs](https://github.com/mdn/yari/issues/4653)
- [x] [Broken macro links rendered as macro text on local Windows build](https://github.com/mdn/yari/issues/4670)
- [x] [Make language switching easier](https://github.com/mdn/yari/issues/4657)
- [x] [Show Tooltips on Icon Hover for Browser Compat Table Icons](https://github.com/mdn/yari/issues/4683)
- [x] [Allow for providing spec URLs when there is no BCD table](https://github.com/mdn/yari/issues/4704)
- [x] [Place language selector at top of the page.](https://github.com/mdn/yari/issues/4740)
- [x] [BCD multiple notes incorrectly formatted](https://github.com/mdn/yari/issues/4757)
- [x] [Local build error for translated-content (macro parsing / h2m macro calls conversion incl. JSON / arrays)](https://github.com/mdn/yari/issues/4744)
- [x] [Issue with "Function.prototype.toString()": Punctuation blends into background for codeblocks in tables](https://github.com/mdn/yari/issues/4647)

#### Latest 10

- [x] [Double-clicking highlights two words instead of one in "Parameters" section of tabs.create() page](https://github.com/mdn/yari/issues/5120)
- [x] [Expand page table of contents to H3s](https://github.com/mdn/yari/issues/5116)
- [x] [developer.mozilla.org/ru/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas](https://github.com/mdn/yari/issues/5115)
- [x] [https://instagram.com/yellp__24?utm_medium=copy_link](https://github.com/mdn/yari/issues/5111)
- [x] [Issue with "BigInt": Left sidebar blends with text](https://github.com/mdn/yari/issues/5105)
- [x] [Chinese document translation error](https://github.com/mdn/yari/issues/5091)
- [x] [Firefox sidebar contains links which are redundant](https://github.com/mdn/yari/issues/5096)
- [x] [Clean up mdn.mozillademos.org file URLs](https://github.com/mdn/yari/issues/1190)
- [x] [Showing which embedded live samples are editable](https://github.com/mdn/yari/issues/5083)
- [x] [Conversion of inline tags to Markdown](https://github.com/mdn/yari/issues/5074)

#### Oldest 5

- [x] [add command to preview a PR](https://github.com/mdn/yari/pull/1677)
- [x] [Add flaw check for innerHTML](https://github.com/mdn/yari/pull/2144)
- [x] [Move _githistory.json files next to index.html / fixes #1990](https://github.com/mdn/yari/pull/2193)
- [x] [Allow URL and pathname for "yarn content edit"](https://github.com/mdn/yari/pull/2273)
- [x] [Doc for unfreezing effort](https://github.com/mdn/yari/pull/2447)

#### Latest 5

- [x] [build(deps-dev): bump eslint-plugin-jest from 25.3.0 to 25.3.3](https://github.com/mdn/yari/pull/5126)
- [x] [build(deps-dev): bump sass from 1.45.1 to 1.45.2](https://github.com/mdn/yari/pull/5125)
- [x] [build(deps-dev): bump @babel/core from 7.16.5 to 7.16.7](https://github.com/mdn/yari/pull/5124)
- [x] [build(deps): bump rehype-raw from 5.1.0 to 6.1.1](https://github.com/mdn/yari/pull/5123)
- [x] [build(deps-dev): bump @types/jest from 27.0.3 to 27.4.0](https://github.com/mdn/yari/pull/5122)
