### ISSUE TITLE
Task List: Sprint 2: Issue and PR Triage

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5156]
# Task List

#### Oldest 10

- [x] [Text overlap](https://github.com/mdn/yari/issues/4772)
- [x] [Improvement: Make links to pages that haven't been translated have a different style](https://github.com/mdn/yari/issues/4784)
- [x] [BCD rendering feature idea: link to Can I Use](https://github.com/mdn/yari/issues/4800)
- [x] [Long word in sidebar class in nav tag](https://github.com/mdn/yari/issues/4795)
- [x] [Rendering issues for WebExtensions/manifest.json on http://localhost:3000](https://github.com/mdn/yari/issues/4654)
- [x] [Improve Subresource Integrity](https://github.com/mdn/yari/issues/4823)
- [x] [Document how popularities.json works](https://github.com/mdn/yari/issues/4864)
- [x] [Automatically add labels to issue when they are raised from MDN](https://github.com/mdn/yari/issues/4496)
- [x] [Create a github action to move issues](https://github.com/mdn/yari/issues/4497)
- [x] [Node database tutorial](https://github.com/mdn/yari/issues/4865)

#### Latest 10

- [x] [Local build error for translated-content (macro parsing / h2m macro calls conversion incl. JSON / arrays)](https://github.com/mdn/yari/issues/4744)
- [x] [Broken macro links rendered as macro text on local Windows build](https://github.com/mdn/yari/issues/4670)
- [x] [Mozilla Demos crammed on small viewport](https://github.com/mdn/yari/issues/1720)
- [x] [Make tables in main page content scrollable at narrow viewport widths (mobile)](https://github.com/mdn/yari/issues/5142)
- [x] [Clean up mdn.mozillademos.org file URLs](https://github.com/mdn/yari/issues/1190)
- [x] [Improve self link broken link flaw checking](https://github.com/mdn/yari/issues/4095)
- [x] [Double-clicking highlights two words instead of one in "Parameters" section of tabs.create() page](https://github.com/mdn/yari/issues/5120)
- [x] [Firefox sidebar contains links which are redundant](https://github.com/mdn/yari/issues/5096)
- [x] [Issue: reported a flaw "MacroWrongXRefError from CSSRef" in ja locale](https://github.com/mdn/yari/issues/5129)
- [x] [Allow for providing spec URLs when there is no BCD table](https://github.com/mdn/yari/issues/4704)

#### Oldest 5

- [x] [add command to preview a PR](https://github.com/mdn/yari/pull/1677)
- [x] [not-prettier flaw](https://github.com/mdn/yari/pull/2621)
- [x] [adding redirects tool guide](https://github.com/mdn/yari/pull/2741)
- [x] [build git-recent-hours](https://github.com/mdn/yari/pull/2908)
- [x] [support move/remove/update for translated content](https://github.com/mdn/yari/pull/2934)

#### Latest 5

- [x] [build(deps): bump dotenv from 10.0.0 to 11.0.0](https://github.com/mdn/yari/pull/5155)
- [x] [Update Learn sidebar for updates to JS objects module](https://github.com/mdn/yari/pull/5152)
- [x] [build(deps-dev): bump sass from 1.46.0 to 1.47.0](https://github.com/mdn/yari/pull/5148)
- [x] [build(deps): bump got from 11.8.3 to 12.0.1](https://github.com/mdn/yari/pull/5147)
- [x] [build(deps): bump fast-xml-parser from 3.21.1 to 4.0.1](https://github.com/mdn/yari/pull/5146)
