### ISSUE TITLE
Task List: Sprint 3: Issue and PR Triage

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5179]
#### Oldest 10

- [x] [Idea: Related content](https://github.com/mdn/yari/issues/4859)
- [x] [Found a possible security concern](https://github.com/mdn/yari/issues/4939)
- [x] [Remove TemplateLink macro](https://github.com/mdn/yari/issues/4848)
- [x] [Yari does not respect markdown paragraphs in bullets/lists](https://github.com/mdn/yari/issues/4828)
- [x] [Research: Let’s consider CSS Modules](https://github.com/mdn/yari/issues/4858)
- [ ] [Content bug: Inexistent web pages for non en-US languages.](https://github.com/mdn/yari/issues/4984)
- [x] [Definition list layout ugly if term contains html element kbd](https://github.com/mdn/yari/issues/4983)
- [ ] [PR review companion seems flaky?](https://github.com/mdn/yari/issues/4972)
- [ ] [Articles with <> in title do not render properly in search engine results](https://github.com/mdn/yari/issues/4961)
- [x] [Label automation from mdn site for new issues not working correctly](https://github.com/mdn/yari/issues/4999)

#### Latest 10

- [x] [Rendering issues for WebExtensions/manifest.json on http://localhost:3000](https://github.com/mdn/yari/issues/4654)
- [x] [Spanish language option breaks navigation ](https://github.com/mdn/yari/issues/5172)
- [x] [Page loading issues with certain language configurations](https://github.com/mdn/yari/issues/5171)
- [x] [one mozilla.org page doesn't load in FF (documentation for css skew)](https://github.com/mdn/yari/issues/5170)
- [x] [Issue: reported a flaw "MacroWrongXRefError from CSSRef" in ja locale](https://github.com/mdn/yari/issues/5129)
- [x] [Issue with "CSS building blocks": Assessments missing in the navigation](https://github.com/mdn/yari/issues/5164)
- [ ] [Create a github action to move issues](https://github.com/mdn/yari/issues/4497)
- [ ] [Document previewing a pull request locally](https://github.com/mdn/yari/issues/5160)
- [ ] [Allow for providing spec URLs when there is no BCD table](https://github.com/mdn/yari/issues/4704)
- [ ] [Document how popularities.json works](https://github.com/mdn/yari/issues/4864)

#### Oldest 5

- [ ] [add command to preview a PR](https://github.com/mdn/yari/pull/1677)
- [ ] [adding redirects tool guide](https://github.com/mdn/yari/pull/2741)
- [ ] [build git-recent-hours](https://github.com/mdn/yari/pull/2908)
- [x] [support move/remove/update for translated content](https://github.com/mdn/yari/pull/2934)
- [ ] [genuinely lazy-load the BCD table(s)](https://github.com/mdn/yari/pull/2992)

#### Latest 5

- [ ] [Themes menu item link to extension workshop](https://github.com/mdn/yari/pull/5089)
- [ ] [Fix translation dashboard showing "Fresher than English" for stale translations](https://github.com/mdn/yari/pull/5068)
- [ ] [Move to ESM](https://github.com/mdn/yari/pull/5017)
- [ ] [Remove all occurrences of {{Draft}} and any references to the 'Draft' KS macro](https://github.com/mdn/yari/pull/4943)
- [ ] [Added Japanese Translations](https://github.com/mdn/yari/pull/4696)
