### ISSUE TITLE
Task List: Sprint 1: Issue and PR Triage

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5216]
#### Oldest 10

- [x] [PR review companion seems flaky?](https://github.com/mdn/yari/issues/4972)
- [x] [Articles with <> in title do not render properly in search engine results](https://github.com/mdn/yari/issues/4961)
- [x] [Use matchMedia or (window.client.height) to dictate some features](https://github.com/mdn/yari/issues/120)
- [x] [Triage all KumaScript macros that are called from our JS docs](https://github.com/mdn/yari/issues/2846)
- [x] [Add feature request property option to github live sample macro](https://github.com/mdn/yari/issues/4354)
- [x] [Change document.title to "Loading..." when changing document](https://github.com/mdn/yari/issues/413)
- [x] [Naming is hard (aka let's talk about the color of the bikeshed)](https://github.com/mdn/yari/issues/979)
- [x] [TS type definitions for docData](https://github.com/mdn/yari/issues/993)
- [x] [Automate the data flow of popularities](https://github.com/mdn/yari/issues/1239)
- [x] [Fix few remaning old live-sample URL's](https://github.com/mdn/yari/issues/1104)

#### Latest 10

- [x] [Remove TemplateLink macro](https://github.com/mdn/yari/issues/4848)
- [x] [Localization differences - Address EmbedLiveSample case with its "localized" argument](https://github.com/mdn/yari/issues/4971)
- [x] [Document previewing a pull request locally](https://github.com/mdn/yari/issues/5160)
- [x] [Issue: reported a flaw "MacroWrongXRefError from CSSRef" in ja locale](https://github.com/mdn/yari/issues/5129)
- [x] [Document how popularities.json works](https://github.com/mdn/yari/issues/4864)
- [x] [Allow for providing spec URLs when there is no BCD table](https://github.com/mdn/yari/issues/4704)
- [x] [[idea] an browser omnibox extension for MDN search with autocomplete](https://github.com/mdn/yari/issues/5193)
- [x] [Rendering issues for WebExtensions/manifest.json on http://localhost:3000](https://github.com/mdn/yari/issues/4654)
- [x] ["Removed in [preview] and later" in compat table seems wrong when added in preview](https://github.com/mdn/yari/issues/5201)
- [x] [Issue with "HTML elements reference": with narrow window text disappears ](https://github.com/mdn/yari/issues/5059)

#### Oldest 5

- [x] [adding redirects tool guide](https://github.com/mdn/yari/pull/2741)
- [ ] [build git-recent-hours](https://github.com/mdn/yari/pull/2908)
- [ ] [support move/remove/update for translated content](https://github.com/mdn/yari/pull/2934)
- [ ] [genuinely lazy-load the BCD table(s)](https://github.com/mdn/yari/pull/2992)
- [ ] [Traits](https://github.com/mdn/yari/pull/3280)

#### Latest 5

- [ ] [Fix inconsistency of image resolution when served from EmbedLiveSample - l10n](https://github.com/mdn/yari/pull/5215)
- [x] [Auto-generate IDs for all <dt> elements](https://github.com/mdn/yari/pull/5190)
- [x] [Themes menu item link to extension workshop](https://github.com/mdn/yari/pull/5089)
- [x] [Fix translation dashboard showing "Fresher than English" for stale translations](https://github.com/mdn/yari/pull/5068)
- [ ] [Move to ESM](https://github.com/mdn/yari/pull/5017)
