### ISSUE TITLE
Testing/QA architecture in Yari

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#624]
This isn't really an issue with a simple remedy but it's worth writing down nevertheless. 

Testing/QA isn't just one single solution. To make Yari reliable and productive we should attack the QA with multiple different approaches. There's no panacea or silver bullet for testing and we should just make sure we attack the problem gently on multiple fronts. 

- [ ] TS/ESLint
- [ ] Unit tests
- [ ] [Functional tests (fixture/sample content)](https://github.com/mdn/yari/issues/635)
- [ ] [End-to-end (headless browser) tests](https://github.com/mdn/yari/issues/511)
- [ ] Test the dev environment (server on-the-fly build, watcher, redirects)
