### ISSUE TITLE
E - Complete preparatory tasks for working with Yari

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#684]
**Description:** 
Miscellaneous preparatory steps for Yari work. Including:
- Tooling for detecting and handling KS flaws (e.g. flaws with docs, possibly list/log files, view errs upon preview). Warning, ignoring and error-ing upon hitting a flaw. (5)
- Preparing Git Repo for Yari
- Investigating possible issues with redirects

**Acceptance Criteria**
- [x] Git repo renamed and ready for use with Yari 
- [x] MySQL content importable into Git / handling archiving exceptions / investigating issues with redirects
- [x] The family of `*xref` macros resolve without error even when the document they refer to does not exist, similar to Kuma except that in this case the link will not be clickable. Currently, they throw an error, which creates a flaw but leaves the macro unresolved.
- [x] Handling of xref macros in Yari Kumascript rendering improved
- [x] All English content has been moved to GitHub

**Comment by escattone** [comment]
This has been done for some time.
