### ISSUE TITLE
E - Create tests for Yari PVP

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#685]
# Description
Add tests for Yari1 PVP workflow. This step is essential so that after release, incoming change/feature requests can be handled sanely. Nice to have ability to run locally. 

# Acceptance Criteria
- [x] foundational framework for functional tests
- [x] foundational framework for unit tests
- [x] foundational framework for end-to-end tests
- [ ] foundational framework for dev env tests
- [ ] foundational framework for static analysis of node code
- [ ] a rough test of macros/building live samples (a test page that renders all macros with special cases)

# Tasks
- [ ] https://github.com/mdn/yari/issues/635
- [ ] https://github.com/mdn/yari/issues/636
- [ ] https://github.com/mdn/yari/issues/511

**Comment by peterbe** [comment]
Too old and vague.
