### ISSUE TITLE
E - Prepare CI for use with Yari

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#686]
**Description**

Continuous Integration needs updates to work with Yari.

**Acceptance Criteria**

- [x] [determine Pros/Cons of various CI to assure it's the right tool for Yari (esp. re: scaling): Travis/Github Actions/Circle CI](https://github.com/mdn/yari/issues/638)
- [x] [builds Yari content in CI](https://github.com/mdn/yari/issues/640)
- [ ] CI validates that the dev env works
