### ISSUE TITLE
E - Implement online preview for PRs (Deployer)

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#688]
**Description**
Assuming (TBD) we want to deploy dev content to the internet, we'll need a deployment tool. NOTE: this is to display a doc only, not the entire site. 

# Acceptance Criteria
- [ ] s3 and/or lambda@edge setup to handle redirects depending on path chosen
- [ ] other preparatory work to convert/port python redirects to work with s3/lambda@edge
- [ ] Infrastructure for deployments has been set up allowing for content to be uploaded and served from S3 (and possibly cloudfront). 
- [ ] As an MDN content team reviewer I can see a PR online
- [ ] As an MDN team member I can see the master branch on staging

**Tasks**
** for PR deployments
- [x] Setup wildcard domain to map to PR buckets
- [x] New domains get added to route53
- [x] Auto purge for s3 pr buckets set up
- [x] lamdba@edge URL to S3 path rewrites
- [ ] lambda@edge question->handling redirects investigated

** For staging deployments
- [ ] Setup S3/Cloudfront (setup infra first)
- [ ] Cloudfront set up to route to s3

**Comment by bershanskiy** [comment]
Did you consider using [GitHub Pages](https://pages.github.com/) as a CDN?
Since there is interest in building content on GitHub Actions in #711, you might end up with infrastructure (scripts) sufficient for building all content in GitHub Actions. After that, it should be trivial to build content on every commit push and push built content to a branch that would be deployed to GitHub Pages.

**Comment by chinikes** [comment]
Epic closed to reflect updated scope of Yari implementation
