### ISSUE TITLE
U - Prepare PVP for release to content team

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#705]
**Acceptance Criteria**
- [x] introduces/describes PVP (what it can/can't do)
- [x] documents installation process
- [x] documents basic document actions - create, update, delete documents
- [x] documents feedback that we're interested in hearing: run-thru of their workflow
- [x] documents known issues/shortcomings/bugs: (the MVP features we haven't done: deploying, deploying a PR, file attachments, security linting, syntax highlighting)
- [x] documenting what we could easily fix/repair in the content (near term/ - automated fixes)
- [x] provide a means/place/slack channel of receiving feedback (Gdoc or otherwise)

**Tasks**
- [x] install Yari over and over
- [x] write documentation
- [x] setup reception channels
