### ISSUE TITLE
For iOS Safari, the color of status bar remains white even if dark mode is on. Because of <meta name="theme-color" content="#ffffff" />

### ISSUE THREAD

**Issue by 3-2** [mdn/yari#7884]
### Summary

There is such a line in [yari/client/public/index.html](https://github.com/mdn/yari/blob/5d95ccd3d4535ba2b06d02012a3e6e47b039f8da/client/public/index.html):
`<meta name="theme-color" content="#ffffff" />`
This code restricts the color of status bar to white in Safari for iOS.

Therefore, status bar remains white even if dark mode is on in iOS, which is glaring at night.

Note: this issue doesn't only happen on `developer.mozilla.org`, but also on `support.mozilla.org`.

### URL

https://developer.mozilla.org

### Reproduction steps

1. Open Safari for iOS.
2. Visit `https://developer.mozilla.org`.
3. Switch dark mode again and again, you can see the color of status bar remains white.

### Expected behavior

The color of status bar follows dark mode.

### Actual behavior

The color of status bar remains white

### Device

Smartphone

### Browser

Safari

### Browser version

Stable

### Operating system

iOS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
@3-2 It looks like the issue is not yet resolved, as [the PR](https://github.com/mdn/yari/pull/9325) is not merged yet.

**Comment by 3-2** [comment]
@caugner 
I'm not familiar with how GitHub operates. I just see the fact that the colour of status bar now meets user expectation under any situation. It’s black under dark mode.
Can you explain why this issue should keep opened? This will help me be familiar with how GitHub operates. Thank you!

**Comment by 3-2** [comment]
Alright, I'm wrong...It really isn't resolved. It's because of the [dark mode extension](https://getnoir.app/) installed on my Safari that make me feel like the issue had been resolved.
Sorry...@caugner

**Comment by caugner** [comment]
@3-2 For your information, this should be resolved in the meantime. 😉
