### ISSUE TITLE
E -  Determine path forward for integrating Yari1 (Github) content with Kuma

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#815]
### **Description:** 
        
The goal of this milestone is to assess how we should move forward regarding rendering Yari generated doc pages (not all pages!) within the Kuma ecosystem. 

This should be a time-boxed exercise. 

The two approaches are:

1. Yari1 template: renders within the context of existing Kuma machinery
Description: keeps more of the old machinery around, would use existing jinja template (with nunjucks mock node jinja), which injects values and calls kuma react based ssr, uses existing suboptimal CSS)

2. Yari2 template: independent of Kuma machinery  
 Description: puts KS-rendered content into yari2 template [react based ssr (does code splitting/bundling done correctly), adds fake header/footer currently, quick css]

### **Acceptance Criteria:**

Please put notes here: [https://docs.google.com/document/d/1WxdKSydtCt1Wttt_i-T49pfI2313Lw50J_dY2YLUXEE/edit#](https://docs.google.com/document/d/1WxdKSydtCt1Wttt_i-T49pfI2313Lw50J_dY2YLUXEE/edit#)

**For approach 1:** 
- [x] A list defining what changes/work/tasks , new features (if any), and deprecations  would be required to get Yari1 content/template to work with Kuma.
- [x] Estimates or t-shirt sizes (S/M/L) for each item on the list above
- [x] Overall, assess developer experience/maintainability of the work you've defined (which will be harder to maintain/change in the short and long-term?) 
- [x] Overall, assess how (if at all) it will change end user experience 
- [x] Overall, assess effects on performance
- [x] If there are multiple possible approaches to each solution (each  with tradeoffs), define those approaches. E.g fast w/high tech debt, slow w/low tech debt.

**For approach 2:** 
- [x] A list defining what tasks, new features (if any), and deprecations would be required to get a Yari2 template (using Yari1 content) to emulate Kuma functionality.
- [x] Estimates or t-shirt sizes (S/M/L) for each item on the list above
- [x] Overall, assess effects on developer experience/maintainability of the work you've defined (which will be harder to maintain/change in the short and long-term?) 
- [x] Overall, assess how (if at all) it will change end user experience 
- [x] Overall, assess effects on performance
- [x] If there are multiple possible approaches to each solution (each  with tradeoffs), define those approaches. E.g fast w/high tech debt, slow w/low tech debt.

**Comment by atopal** [comment]
The decision was to go with Approach 2.
