### ISSUE TITLE
U - File attachment linting & builds pages with rendered attachment

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#854]
This attempts to list the kinds of things we can write automation on that checks file attachments. The ultimate goal is to use code/automation to avoid getting bad stuff into the `master` branch and going into production. E.g. insecure or corrupt or wasteful attachments.

# Acceptance Criteria
- [x] If the file extension is not recognized do not add file
- [x] If it's 0 bytes or greater than $MAX_FILE_SIZE
- [x] If it's a .svg, check that it doesn't contain any "scripts"
- [x] Does the file extension match the format? E.g. compare binary headers with the file extension.
- [x] Check that the file attachment is mentioned in any document and not just an orphan
- [x] All file attachments and all references to them should be all lowercase. 
- [x] [Attachment renders in the build](https://github.com/mdn/yari/issues/975)

Other things for the future:
- [x] If it's an image, can it be compressed losslessly by over 20%(*) if so, it should have been compressed by the author.(**)
- [ ] Check for nudity in images
- [ ] Check that the image dimensions are sane

(*) Remains to be pinpointed more exactly and it might become configurable.
(**) How we do that, it'll be some script that's part of the Yari repo so the author of the PR should technically have access to run the same thing as the linter did on her laptop so she can fix the image and amend the PR by another git commit.

**Comment by peterbe** [comment]
One thing to think about is; should we hard require that all file attachment references should always be in the same directory. 
If you do, inside `./thispage/index.html` add this: `<img src="../siblingpage/screenshot.png">`, it would work but now that `../siblingpage` might not know that it's so important and if you now rename it you would break things. 

In a sense, it all depends on localized/translated content. Because it's totally realistic that in `/content/files/fr/some/page/index.html` you'd want to have `<img src="/en-US/docs/Some/Page/screenshot.png">` instead of every translated version having its own copy of the file. 

But you could make a rule and say that `if (locale === 'en-US') { beAnalAboutRelativeFilePaths() }`.

**Comment by peterbe** [comment]
Next action for me; Analyze how feasible this is. I.e. is it super common that documents refer to images in a very many-to-many fashion within `en-us`.

**Comment by peterbe** [comment]
Note-to-self; After talking to @escattone about this at length; we've concluded that most of these lintings are, technically, more "validators". Linting sounds like it's "not great, but ok'ish". No, we're *not* OK to let any image into the build if it's a wolf in sheep's clothing. 

I.e. checking that a `screenshot.png` really is a PNG (and ignoring the file name extension) and if it's not, throw a new error that should break the build. 

Note that the above list of acceptance criteria are all good checks to make but some of them are flaws and some of them are validation (aka. break the build potentially).

**Comment by peterbe** [comment]
Still some to do but let's track in https://github.com/mdn/yari/issues/1103 instead.
