### ISSUE TITLE
E - Make existing Yari PVP code production-ready

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#877]
## Description

The existing Yari prototype was built quickly and roughly in order to get it out the door. Because of that, certain things were rushed or not given the attention they needed or deserved, such as: software architecture, security concerns, build times, stability, ADRs (documentation). Also: Yari broken in Linux, needs to be fixed.

## Acceptance Criteria

- [x] Documentation in the form of ADRs, system architecture or diagrams are written (gregor)
- [x] Refactorings applied from learnings from documentation (gregor)
- [ ] Separate code from content in git (gregor)

**Comment by tobinmori** [comment]
@tobinmori 

these need a new epic:

yari#901U - Fundamental redirects ported to Yari4
yari#902U - Determine path forward for doc 'summary' field

**Comment by chinikes** [comment]
Epic closed based on updated Yari implementation backlog
