### ISSUE TITLE
E - CMS scope defined and delivered

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#878]
## Description: 

We probably need some CMS capabilities. The goal is to define the minimum set of requirements and to implement those. CMS in this context means: 
* redirects
* editing of documents
* creating docs
* deleting docs
* moving docs
* tagging
* searching

## Acceptance Criteria:

- [ ] Decision whether we should have just a CLI and no GUI
- [ ] Decision on the subset of the CMS functions above
- [ ] A list defining and prioritizing the featureset delta between the Yari and existing Kuma (what features are currently missing from Yari)
- [ ] Update tooling to cover the above

**Comment by chinikes** [comment]
Epic closed to reflect updated scope of Yari implementation
