### ISSUE TITLE
E - Investigate & Implement File Attachments in Yari

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#904]
# Epic 
E - Investigate & Implement File Attachments in Yari so that we can use file attachments in Yari 

# Description
File attachments will be checked into Git, but we need to make sure that attachments are vetted: valid, secure, compressed, actually used. 

# Acceptance Criteria 
- [ ] Automated security checks implemented (corrupt/insecure files/check svgs for scripts)
- [ ] Automated compression
- [ ] Automated basic file checks: for empty files, file format matches extensions
- [ ] Automated checks that file is actually used in docs
- [ ] Writers can reference the file attachments in the documents

**Comment by peterbe** [comment]
Note-to-self; We should at least look into use https://github.com/marketplace/imgbot/ to maybe have it send PRs to us about files checked in. Rather than having to write our own Node wrappers for these things.

**Comment by Gregoor** [comment]
I kind of think we'd want the opposite of what Imgbot does. We want something that gatekeeps and optimizes incoming PRs so that unoptimized images never even make it into our main branch's history, no?

**Comment by peterbe** [comment]
> I kind of think we'd want the opposite of what Imgbot does. We want something that gatekeeps and optimizes incoming PRs so that unoptimized images never even make it into our main branch's history, no?

1. I wonder if you can ask `ImgBot` to only concern itself with images that appear in open PRs. 
2. Ideally, we shouldn't ever allow them in at all when they *could* be optimized (but the writer is arguably "lazy") but ImgBot presents an opportunity to save ourselves some time. 

Truth be told, writing some Node + `package.json` stuff that does lossless image compression isn't that hard. Let's see what shakes out.
