### ISSUE TITLE
E - Admin and contribution guide for Yari written

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#934]
## Description
For each item in the MDN admin guide and the contribution guide, we need a corresponding item in the Yari admin guide, so that writers can look up common and uncommon steps they need to do their job. Includes tagging, the summary and all other front-matter, renaming and redirecting, on how to create the TOC (manually inserting IDs?)

## Acceptance Criteria
- [ ] Yari contribution guide draft published internally with a section for every item in the Kuma contribution guide
- [ ] Yari admin guide draft published internally with a section for every item in the Kuma admin guide
- [ ] Things that we know will have to be addressed in Yari admin and contribution guide are called out
- [ ] Team feedback integrated
- [ ] Follow up epics, user stories, tasks are filed

## Tasks
- Look at Admin/Contribution guide to determine unknown unknowns regarding Yari
- Call out unclear items/workarounds to define scope of CMS and missing features.
- After defining scope come back to admin/contribution guide.

**Comment by chinikes** [comment]
Epic closed to reflect updated scope of Yari implementation
