### ISSUE TITLE
fix and improve Open Graph HTML meta tags

### ISSUE THREAD

**Issue by glmvc** [mdn/yari#9429]
### Summary

I was working with og meta tags some time ago and noticed an incorrect value, which I described in more detail in [this issue](https://github.com/mdn/yari/issues/8594).
As I was investigating this further today, I came across more things that should be adjusted and are not quite correct atm:
1. incorrect `og:locale` values, described in the [mentioned issue](https://github.com/mdn/yari/issues/8594)
    - format `language_TERRITORY` (see [Open Graph protocol](https://ogp.me/#optional))
    - example: on MDN sites the set lang code is `fr` for French, but it has to be `fr_FR`, respecting the protocol
2. the `og:locale` value is _not_ updated when the language is changed (language switcher menu), and therefore does _not_ match the language of the document (`<html lang="[LANGCODE]">`) at the given time
    - after reloading the page, `og:locale` gets the language value of the document (which is not the correct value as stated in 1.)
3. as the [Open Graph protocol](https://ogp.me/#structured) suggests, if `og:image` is present, `og:image:alt` should also be specified - this is currently not the case
    - it seems that the [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/) finds some weird image alt text (see screenshot below)
    - I couldn't figure out on the fly if it's cache or the like, but I think it should be checked anyway?

![Screenshot 2023-08-01 at 21 14 23](https://github.com/mdn/yari/assets/95487764/2f57f38d-381f-4bc2-bb8f-9bbef260d89b)

### URL

all pages (also translated pages); for example:
- https://developer.mozilla.org/en-US/
- https://developer.mozilla.org/en-US/docs/Web/CSS
- https://developer.mozilla.org/fr/docs/Learn/HTML

### Reproduction steps

check the mentioned `og` meta tags in the loaded source (dom)

### Expected behavior

- correct language codes for `og:locale`
- use of correct `og:image:alt` text

### Actual behavior

incorrect values for the mentioned og meta tags (regarding the protocol)

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).
