### ISSUE TITLE
Add Mastodon icon link on the footer

### ISSUE THREAD

**Issue by shuuji3** [mdn/yari#9688]
Hello, this is my first time contribution to Yari! 🙂 

Currently, I'm going to create a PR that replaces the Twitter icon link with the newly created Mastodon icon link.

But I'm not sure this aligns with the MDN team's plan. Does the MDN team plan to continue using the Twitter account (https://twitter.com/mozdevnet) to post any other tweets if needed?

This is just my personal opinion, but I'm a bit afraid that keeping using that platform, which seems to be conflicting with MDN/Mozilla and our seeking idea of the Open Web, might end up sending a false message or giving an endorsement for that platform, to the open community.

However, I won't disagree if MDN still needs it for now. In that case, I'll soon revert the removal change and I plan to place a new Mastodon icon to the left of the existing Twitter icon. Please tell me which change is appropriate. Thank you.

### Validations

- [x] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [x] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) that reports the same bug to avoid creating a duplicate.
- [x] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).
```[tasklist]
### Tasks
- [ ] Decide for design of new matodon icon with help of UX
```

**Comment by s-sood** [comment]
Hi @shuuji3 Thank you for you for the idea.

We currently have a good number of followers on Twitter so we wouldn't want to replace it completely with mastodon but would like to wait and see how the two platforms evolve. That being said, instead of replacing Twitter icon with Mastodon - we will be adding a new icon for Mastodon.

**Comment by shuuji3** [comment]
Thanks for taking a look. OK, I understand. :+1: Let me update the current PR. I think I can do later today.

**Comment by shuuji3** [comment]
OK, now updated the PR. Please see the comment on the PR: https://github.com/mdn/yari/pull/9689#issuecomment-1757687999

Feel free to merge whenever you are comfortable. Thanks!
