### ISSUE TITLE
U - Prepare S3 infra for deployments

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#969]
# Acceptance Criteria
- [ ] Infrastructure for deployments has been set up allowing for content to be uploaded and served from S3 and cloudfront. 

# Tasks
- [x] Setup S3/Cloudfront (setup infra first)
- [x] Setup wildcard domain to map to PR buckets
- [x] Cloudfront set up to route to s3
- [x] New domains get added to route53
- [x] Auto purge for s3 pr buckets set up

**Comment by escattone** [comment]
The infrastructure for this has been created and tested:
- [x] The Route53 hosted zone for `dev.mdn.mozit.cloud` (already existed)
- [ ] CloudFront `MDN Primary dev CDN` with CNAME `*.content.dev.mdn.mozit.cloud` and a single default behavior
- [ ] `*.content` wildcard DNS record (within the `dev.mdn.mozit.cloud` hosted zone) that points to the `MDN Primary dev CDN`
- [ ] Wildcard SSL cert for ` *.content.dev.mdn.mozit.cloud`, attached to the `MDN Primary dev CDN`
- [ ] Initial version of the Lambda function `mdn-content-origin-request` that translates incoming URL's into proper S3 key by also taking into account the lowest-level portion of the incoming domain (e.g., sets the prefix to `pr123` if the incoming domain is `pr123.content.dev.mdn.mozit.cloud`)
- [ ] The latest published version of the `mdn-content-origin-request` Lambda function attached to the `MDN Primary dev CDN` as an origin-request handler
